name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: 'Source'
        clangFormatVersion: 12

  build:
    runs-on: self-hosted
    container:
      image: cloud.canister.io:5000/jeevcat/ue4-full:4.27.0-linux
      options: --user root -v ${{ github.workspace }}:${{ github.workspace }}:rw
      credentials:
         username: jeevcat
         password: ${{ secrets.CANISTER_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Package plugin
        run: ue4 package -NoPCH -NoSharedPCH -DisableUnity

      - uses: actions/upload-artifact@v2
        with:
          name: packaged
          path: dist
